'use strict';
/* ═══════════════════════════════════════════════════════════════════════════
   IMPROVEMENT, THE ROADMAP, AND EXPERT SUPPORT                    (Run 63/P9)
   ───────────────────────────────────────────────────────────────────────────
   Two page routes. Every JSON endpoint for these modules lives in
   routes/api.js under the existing `/api` mount — recurring-bugs-checklist #17:
   requireAuth's `/api/` prefix test is only as good as its premise, and a JSON
   route served from a router mounted at `/` gets the 302 meant for a page
   navigation, after which the caller parses the login page as JSON and reports
   the feature as unavailable.

   ── WHAT /improvement IS ─────────────────────────────────────────────────
   The page that answers "why is my score what it is, and what do I do about
   it". It was the one question the product could not answer anywhere: the
   dashboard showed three recommendations with no account of the other
   thirty-odd, and the assessment result showed a list of questions with no
   account of what any of them was worth.

   Four sections, in the order the directive names them:
     1  CURRENT POSITION — the score, and what it was computed against
     2  STRONG AREAS and PRIORITY GAPS — per pillar, from the engine's figures
     3  THE ROADMAP — the ten-rung ladder, each rung saying how it is joined
        to the one above
     4  THE GAPS — every one, with its five answers

   ── WHAT /consultation IS, AND WHAT IT IS NOT ────────────────────────────
   It is not a booking page. There is no availability, no calendar, no fee and
   no record of a session anywhere in this platform, and the page says so in
   those words. What it does is explain WHY the platform thinks expert guidance
   might help — six configured triggers, each naming the rows it fired on and
   the threshold it crossed — so the recommendation is checkable rather than
   asserted.

   NO NEW CSS. Every class here is from §26–§29 of the ESG layer or from the
   master, and each was grepped for before it was written.
   ═══════════════════════════════════════════════════════════════════════════ */

const express = require('express');
const { layout, esc, emptyState, icon } = require('../utils/layout');
const journey = require('../services/journeyEngine');
const gapAnalysis = require('../services/gapAnalysis');
const roadmapService = require('../services/roadmapService');
const readinessService = require('../services/readinessService');
const consultation = require('../services/consultationTriggers');
const view = require('../utils/actionView');

const router = express.Router();

// Express 4 hangs a request forever on an unhandled rejection instead of
// 500-ing, which reads as a network fault and logs nothing worth reading.
const wrap = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
const cid = (req) => req.user && req.user.company_id;

/* ═══════════════════════════════════════════════════════════════════════════
   /improvement
   ═══════════════════════════════════════════════════════════════════════════ */
router.get('/improvement', wrap(async (req, res) => {
  const companyId = cid(req);
  const live = await journey.loadLiveAssessment(companyId);
  const assessmentId = live ? live.id : null;

  /* ONE GAP ANALYSIS, RENDERED TWICE — not two analyses.
     This used to run gapAnalysis.analyse() here and let roadmapService.build()
     run it again, which measured as six duplicated statements per render and
     put two independently-derived figures on one page. The roadmap is handed
     the result instead. */
  const gaps = await gapAnalysis.analyse(companyId, assessmentId);
  const road = await roadmapService.build(companyId, assessmentId, { gaps });

  const header = `
    <header class="esg-page-header esg-enter">
      <div class="esg-page-header__text">
        <h2 class="esg-h1">Improvement</h2>
        <p class="esg-page-header__intro">Why your score is what it is, what would move it, and
          where that leads. Every point figure on this page was computed by the scoring engine at
          the weighting version stamped on your score — none of it is generated by AI, and none of
          it is computed twice.</p>
      </div>
    </header>`;

  /* ── 1 · CURRENT POSITION ────────────────────────────────────────────── */
  const position = (() => {
    if (gaps.state === 'no_assessment') {
      return emptyState('instrumented_but_empty', {
        title: 'No assessment has been started',
        body: 'Gaps are the scoring engine’s own output, so there is nothing to explain until an '
            + 'assessment exists and has been scored. Scoring is switched on and working — there '
            + 'is simply nothing to score, and no provisional figure is being estimated in the '
            + 'meantime.' });
    }
    if (gaps.state === 'incomplete_score') {
      /* A SCORE SET WITH NO OVERALL ROW. Rare — the engine writes every scope
         in one transaction — and it used to reach the line below and throw on
         a null. Named rather than guarded, so the page says what happened. */
      return emptyState('uninstrumented', {
        title: 'This assessment’s score is incomplete',
        body: gaps.detail });
    }
    if (gaps.state === 'not_scored') {
      return emptyState('instrumented_but_empty', {
        title: 'This assessment has not been scored yet',
        body: 'The gaps on this page are produced by the scoring engine when it runs. Until it '
            + 'does there is no list, and this platform will not guess a provisional one. Finish '
            + 'the assessment and calculate the score.' });
    }
    const o = gaps.overall;
    return `<div class="esg-facts">
      <div class="esg-fact">
        <span class="esg-fact__label">Current position</span>
        <span class="esg-fact__value esg-num">${esc(Math.round(o.score))}</span>
        <span class="esg-fact__from">Out of 100 · band ${esc(o.band_code)}${
  o.band_label ? ` · ${esc(o.band_label)}` : ''}</span>
      </div>
      <div class="esg-fact">
        <span class="esg-fact__label">Unearned points</span>
        <span class="esg-fact__value esg-num">${esc(gaps.counts.points_missed)}</span>
        <span class="esg-fact__from">Summed from the engine’s own per-disclosure figures</span>
      </div>
      <div class="esg-fact">
        <span class="esg-fact__label">Disclosures with a gap</span>
        <span class="esg-fact__value esg-num">${esc(gaps.counts.total)}</span>
        <span class="esg-fact__from">${esc(gaps.counts.unanswered)} not answered ·
          ${esc(gaps.counts.unevidenced)} with nothing attached ·
          ${esc(gaps.counts.partial)} partly met</span>
      </div>
      <div class="esg-fact esg-fact--text">
        <span class="esg-fact__label">Computed at</span>
        <span class="esg-fact__value">Weighting ${esc(o.weighting_version)}</span>
        <span class="esg-fact__from">Framework ${esc(o.framework_version)} · engine ${esc(o.engine_version)}</span>
      </div>
    </div>`;
  })();

  /* ── 2 · STRONG AREAS AND PRIORITY GAPS ───────────────────────────────
     STRONG is a claim, so the page states the test it had to pass rather than
     leaving a reader to infer a threshold. A pillar with nothing outstanding
     is a real result and it is different from a pillar that merely scored
     well. */
  const pillarSection = gaps.state !== 'ok' ? '' : `
    <section class="esg-section esg-enter" style="--esg-i:2">
      <div class="esg-section__head">
        <h3 class="esg-section__title">Strong areas and priority gaps</h3>
        <span class="esg-section__note">Per pillar, from the engine’s per-disclosure figures</span>
      </div>
      <div class="esg-card"><div class="esg-card__body esg-stack">
        ${gaps.pillars.strong.length
    ? `<div class="esg-rec">
             <span class="esg-rec__head">Strong: ${gaps.pillars.strong.map((p) => esc(p.name)).join(', ')}</span>
             <p class="esg-rec__text">Every applicable indicator is answered and no weighted point
               is unearned. That is a stronger statement than a high score — a pillar can score
               well and still be carrying gaps.</p>
           </div>`
    : `<div class="esg-rec">
             <span class="esg-rec__head">No pillar is fully clear yet</span>
             <p class="esg-rec__text">A pillar is called strong here only when every applicable
               indicator is answered AND no weighted point is unearned in it. None currently
               passes both tests, which is a measured result rather than a judgement.</p>
           </div>`}
        <div class="esg-table-scroll" tabindex="0" role="region" aria-label="Gaps by pillar">
          <table class="esg-table esg-table--stack">
            <thead><tr><th>Pillar</th><th>Score</th><th>Answered</th><th>Unearned points</th><th>Gaps</th></tr></thead>
            <tbody>
              ${gaps.pillars.all.map((p) => `<tr>
                <td data-label="Pillar">${esc(p.name)}</td>
                <td data-label="Score" class="esg-td-num">${esc(Math.round(p.score))}</td>
                <td data-label="Answered" class="esg-td-num">${esc(p.answered)} / ${esc(p.applicable)}${
  p.na ? ` <span class="esg-small">(${esc(p.na)} n/a)</span>` : ''}</td>
                <td data-label="Unearned points" class="esg-td-num">${esc(p.points_missed)}</td>
                <td data-label="Gaps">${esc(p.gaps)}${p.gaps
    ? ` <span class="esg-small">${esc(p.unanswered)} unanswered, ${esc(p.unevidenced)} unevidenced, ${esc(p.partial)} partial</span>`
    : ''}</td>
              </tr>`).join('')}
            </tbody>
          </table>
        </div>
      </div></div>
    </section>`;

  /* ── 3 · THE ROADMAP ─────────────────────────────────────────────────── */
  const roadmapSection = `
    <section class="esg-section esg-enter" style="--esg-i:3">
      <div class="esg-section__head">
        <h3 class="esg-section__title">Where this leads</h3>
        <span class="esg-section__note">Every rung says how it is joined to the one above</span>
      </div>
      <div class="esg-card"><div class="esg-card__body esg-stack">
        <p class="esg-small esg-prose">Three of these rungs are <strong>computed</strong> from the
          rung above them and one is <strong>joined by a column in the database</strong>. The rest
          are simply the next step in the product, and the ladder says so on each — a line drawn
          between two things is not evidence that one caused the other, and this platform will not
          use a layout to imply what its data does not support.</p>
        ${view.roadmap(road.steps)}
      </div></div>
    </section>`;

  /* ── 4 · THE GAPS ────────────────────────────────────────────────────── */
  const gapSection = gaps.state !== 'ok' ? '' : (gaps.gaps.length ? `
    <section class="esg-section esg-enter" style="--esg-i:4">
      <div class="esg-section__head">
        <h3 class="esg-section__title">Every gap, and what would resolve it</h3>
        <span class="esg-section__note">${esc(gaps.gaps.length)} disclosure${
  gaps.gaps.length === 1 ? '' : 's'} · ordered by the points each is costing</span>
      </div>
      <div class="esg-gaps">
        ${gaps.gaps.map((g, i) => view.gapCard(g, i)).join('')}
      </div>
    </section>` : `
    <section class="esg-section esg-enter" style="--esg-i:4">
      <div class="esg-section__head">
        <h3 class="esg-section__title">Every gap, and what would resolve it</h3>
      </div>
      ${emptyState('zero', {
    title: 'Every scorable point is earned',
    body: 'The scoring engine found no disclosure carrying an unearned point on this assessment. '
        + 'That is a measured result — the gap list is empty rather than switched off.' })}
    </section>`);

  /* ── 5 · WHAT THIS PAGE DELIBERATELY DOES NOT DO ─────────────────────── */
  const absences = `
    <section class="esg-section esg-enter" style="--esg-i:5">
      <div class="esg-section__head">
        <h3 class="esg-section__title">What this page deliberately does not do</h3>
        <span class="esg-section__note">Absent, and said out loud</span>
      </div>
      <div class="esg-card"><div class="esg-card__body">
        <div class="esg-rec"><span class="esg-rec__head">It does not predict your new score</span>
          <p class="esg-rec__text">Closing a gap worth 2.4 points does not add 2.4 to your score.
            The overall figure renormalises pillar weights across the pillars that are actually
            scorable, so the effect of any one change depends on every other answer. The engine
            recomputes the whole thing when you ask it to; nothing here estimates the outcome in
            advance.</p></div>
        <div class="esg-rec"><span class="esg-rec__head">It does not assign the work</span>
          <p class="esg-rec__text">This platform records who last answered a question and has no
            owner, reviewer or approver field. Every gap says so rather than nominating a role it
            cannot see.</p></div>
        <div class="esg-rec"><span class="esg-rec__head">It does not claim a project fixes a gap</span>
          <p class="esg-rec__text">The AI opportunity scan is told your profile, which carbon
            categories you hold and whether each indicator is answered. It is never told your gaps,
            never asked which one to address, and proposes only from a fixed list of project types.
            A suggestion is for your company; it is not an answer to a disclosure.</p></div>
      </div></div>
    </section>`;

  res.send(layout('Improvement', `
    <div class="esg-page">
      ${header}
      <section class="esg-section esg-enter" style="--esg-i:1">
        <div class="esg-section__head">
          <h3 class="esg-section__title">Current position</h3>
          <span class="esg-section__note">${gaps.state === 'ok'
    ? `${esc(gaps.overall.answered)} of ${esc(gaps.overall.applicable)} applicable indicators answered`
    : 'Not scored yet'}</span>
        </div>
        ${position}
      </section>
      ${pillarSection}
      ${roadmapSection}
      ${gapSection}
      ${absences}
    </div>`, req.user, '/improvement'));
}));

/* ═══════════════════════════════════════════════════════════════════════════
   /consultation
   ═══════════════════════════════════════════════════════════════════════════ */
router.get('/consultation', wrap(async (req, res) => {
  const companyId = cid(req);
  const live = await journey.loadLiveAssessment(companyId);
  const ready = await readinessService.calculate(companyId);
  const c = await consultation.evaluate(companyId, live ? live.id : null, ready);

  /* THE BOOKING STATE IS THE FIRST THING ON THE PAGE, NOT A FOOTNOTE.
     A page that opens with "here is why you might want an expert" and mentions
     three screens down that none can be booked is an advertisement. The order
     is deliberate: what does not exist, then what the platform noticed. */
  const notBuilt = `
    <div class="esg-reserved">
      <span class="esg-reserved__mark" aria-hidden="true">${icon('governance')}</span>
      <div>
        <h3 class="esg-reserved__title">There is no consultation module on this platform</h3>
        <p class="esg-reserved__body">${esc(c.booking.detail)} What is below is not an offer and
          nothing on this page schedules anything. It is an account of what the platform noticed
          in your own data, so that you can decide for yourself whether it is worth taking to
          somebody.</p>
      </div>
      <span class="esg-reserved__status">Not built</span>
    </div>`;

  const why = c.recommended ? `
    <section class="esg-section esg-enter" style="--esg-i:2">
      <div class="esg-section__head">
        <h3 class="esg-section__title">Why support might be worth it</h3>
        <span class="esg-section__note">${esc(c.triggers.length)} of ${esc(c.considered)}
          configured situations apply</span>
      </div>
      <div class="esg-actions">
        ${c.triggers.map((t, i) => `<article class="esg-action esg-action--recommended" style="--esg-i:${esc(i)}">
          <div class="esg-action__head">
            <span class="esg-action__state">${esc(t.area)}</span>
            <h3 class="esg-action__what">${esc(t.label)}</h3>
          </div>
          <p class="esg-action__why">${esc(t.support)}</p>
          <p class="esg-action__basis">${esc(t.because)}</p>
        </article>`).join('')}
      </div>
    </section>` : `
    <section class="esg-section esg-enter" style="--esg-i:2">
      <div class="esg-section__head">
        <h3 class="esg-section__title">Why support might be worth it</h3>
        <span class="esg-section__note">None of the ${esc(c.considered)} configured situations applies</span>
      </div>
      ${emptyState('zero', {
    title: 'Nothing in your data suggests you need help right now',
    body: 'All six situations were checked against your own rows and none crossed its threshold. '
        + 'That is a measured result and not an absence of checking — the six rules and the '
        + 'figures they were tested against are listed below.' })}
    </section>`;

  const areas = c.areas.length ? `
    <section class="esg-section esg-enter" style="--esg-i:3">
      <div class="esg-section__head">
        <h3 class="esg-section__title">Key areas</h3>
        <span class="esg-section__note">Derived from what applied, not a fixed menu</span>
      </div>
      <div class="esg-card"><div class="esg-card__body">
        <div class="esg-pillars-named">
          ${c.areas.map((a) => `<span class="esg-pillar-name">${esc(a)}</span>`).join('')}
        </div>
      </div></div>
    </section>` : '';

  /* EVERY RULE, AND THE FIGURE IT WAS TESTED AGAINST — including the ones that
     did not fire. A recommendation whose rule you cannot see is a conclusion
     you have to take on trust, and the directive's whole point is that a
     priority must be explainable. */
  const rules = `
    <section class="esg-section esg-enter" style="--esg-i:4">
      <div class="esg-section__head">
        <h3 class="esg-section__title">The six rules, and what your data measured</h3>
        <span class="esg-section__note">Configured in one file, and printed here so they are checkable</span>
      </div>
      <div class="esg-card"><div class="esg-card__body esg-stack">
        <p class="esg-small esg-prose">None of these is about your score. A score is a summary,
          and a summary is the worst possible trigger for advice — a company at a high score with
          every disclosure unreconciled needs more help than one at a lower score with a clean,
          fully evidenced assessment.</p>
        <div class="esg-table-scroll" tabindex="0" role="region" aria-label="Consultation triggers">
          <table class="esg-table esg-table--stack">
            <thead><tr><th>Situation</th><th>Area</th><th>Applies</th></tr></thead>
            <tbody>
              ${consultation.TRIGGERS.map((t) => {
    const fired = c.triggers.find((x) => x.code === t.code);
    return `<tr>
                  <td data-label="Situation">${esc(t.label)}</td>
                  <td data-label="Area">${esc(t.area)}</td>
                  <td data-label="Applies">${fired
      ? `<span class="esg-astate esg-astate--review">Yes</span>
                         <span class="esg-small">${esc(fired.because)}</span>`
      : '<span class="esg-astate esg-astate--na">No</span>'}</td>
                </tr>`;
  }).join('')}
            </tbody>
          </table>
        </div>
      </div></div>
    </section>`;

  const next = `
    <section class="esg-section esg-enter" style="--esg-i:5">
      <div class="esg-section__head">
        <h3 class="esg-section__title">What you can do here instead</h3>
        <span class="esg-section__note">Real destinations, inside this platform</span>
      </div>
      <div class="esg-card"><div class="esg-card__body esg-stack">
        <p class="esg-small esg-prose">Nothing on this page books anything. These are the screens
          that hold the material an adviser would ask for, so that a conversation — whenever and
          however it happens — starts from your own rows rather than from scratch.</p>
        <div class="esg-row">
          <a class="btn btn-outline" href="/improvement">Open the gap list</a>
          <a class="btn btn-outline" href="/green-finance/readiness">Open finance readiness</a>
          <a class="btn btn-outline" href="/documents">Open the evidence</a>
        </div>
      </div></div>
    </section>`;

  res.send(layout('Expert support', `
    <div class="esg-page">
      <header class="esg-page-header esg-enter">
        <div class="esg-page-header__text">
          <h2 class="esg-h1">Expert support</h2>
          <p class="esg-page-header__intro">Whether the platform thinks a conversation with somebody
            would help, why it thinks so, and what it cannot do about it.</p>
        </div>
      </header>
      <section class="esg-section esg-enter" style="--esg-i:1">
        <div class="esg-stack">${notBuilt}</div>
      </section>
      ${why}
      ${areas}
      ${rules}
      ${next}
    </div>`, req.user, '/consultation'));
}));

/* ═══════════════════════════════════════════════════════════════════════════
   /explain — ONE CONTEXTUAL ANSWER, SERVER-RENDERED               (Run 63/P9)
   ───────────────────────────────────────────────────────────────────────────
   The page half of the copilot. There is deliberately no client-side fetch, no
   spinner, no streaming and no chat transcript:

   · A model call costs money and takes a second. Rendering it on a navigation
     the user chose means exactly one call per deliberate click, rather than
     thirty-nine on an assessment page load.
   · A page that works with JavaScript switched off cannot ship the RULE 6
     shape a fetch invites — `fetch(...).then(r => r.json()).catch(() => ({}))`
     is the exact substitute-value pattern this repo's two guards exist to keep
     out, and the surest way not to write it is not to need it.
   · The answer is either the model's or the platform's deterministic one, and
     both are rendered the same way with a line saying which. There is no third
     state where the page shows nothing while it waits.

   IT IS A GET AND IT CALLS A MODEL, which the API route deliberately refuses
   to be. The difference is that this one is a NAVIGATION — a browser
   prefetches links it thinks the user will click, and the exposure here is one
   short call for a company that is already logged in and already on the
   assessment page, against a page that must work without scripting. The API
   equivalent stays a POST for callers that are not browsers.

   `back` IS VALIDATED AS A LOCAL PATH. A returned-to URL taken from a query
   string is an open redirect if it is used as given; this one is only ever
   rendered as an href and only when it starts with a single '/', which rules
   out both an absolute URL and a protocol-relative '//host' one.
   ═══════════════════════════════════════════════════════════════════════════ */
const copilot = require('../services/copilotService');

/** A path this application can safely link back to, or null.
 *
 *  Null rather than a default: the caller renders "back to the dashboard" for
 *  null, which is a real destination, and quietly substituting one for an
 *  attacker-supplied value would hide that anything was rejected. */
function localPath(raw) {
  const v = String(raw || '');
  if (!v.startsWith('/')) return null;
  if (v.startsWith('//')) return null;      // protocol-relative — an absolute URL
  if (v.includes('\\')) return null;        // some parsers read a backslash as a slash
  return v;
}

router.get('/explain', wrap(async (req, res) => {
  const intent = String(req.query.intent || '');
  const subjectId = String(req.query.subject || '');
  const back = localPath(req.query.back);
  const def = copilot.INTENTS[intent];

  const shell = (title, inner, note) => layout(title, `
    <div class="esg-page">
      <header class="esg-page-header esg-enter">
        <div class="esg-page-header__text">
          <h2 class="esg-h1">${esc(title)}</h2>
          <p class="esg-page-header__intro">${esc(note)}</p>
        </div>
      </header>
      <section class="esg-section esg-enter" style="--esg-i:1">${inner}</section>
      <section class="esg-section esg-enter" style="--esg-i:2">
        <div class="esg-row">
          <a class="btn btn-outline" href="${esc(back || '/dashboard')}">${
  back ? 'Back to where you were' : 'Back to the dashboard'}</a>
        </div>
      </section>
    </div>`, req.user, '/assessment');

  if (!def) {
    // A closed vocabulary, and the error names it rather than echoing what was
    // sent — a caller learns the four intents from the refusal.
    return res.status(400).send(shell('Not something the copilot answers',
      emptyState('zero', {
        title: 'That is not one of the four questions',
        body: `The copilot answers exactly four: ${copilot.INTENT_CODES
          .map((c) => copilot.INTENTS[c].label).join('; ')}. It is not a general assistant and `
          + 'there is deliberately no free-text box.' }),
      'The copilot has a closed vocabulary.'));
  }

  let answer;
  try {
    answer = await copilot.ask({ companyId: cid(req), userId: req.user.id, intent, subjectId });
  } catch (err) {
    // A subject this company cannot see is a 404 and says so. Rendering an
    // empty answer would make an authorisation failure look like a model that
    // had nothing to say.
    if (/no .* this company can see/.test(err.message) || /is required/.test(err.message)) {
      return res.status(404).send(shell(def.label,
        emptyState('zero', {
          title: 'Nothing here matches that',
          body: `The copilot was asked about a ${def.subject} this company cannot see. Nothing was `
              + 'sent to a model.' }),
        'Nothing was found to answer about.'));
    }
    throw err;
  }

  const subjectBlock = `
    <div class="esg-facts">
      <div class="esg-fact esg-fact--text">
        <span class="esg-fact__label">${esc(answer.subject.kind === 'indicator' ? 'Disclosure'
    : answer.subject.kind === 'document' ? 'Document' : 'Pillar')}</span>
        <span class="esg-fact__value">${esc(answer.subject.code ? `${answer.subject.code} · ` : '')}${
  esc(answer.subject.name)}</span>
        <span class="esg-fact__from">${answer.subject.mapping_status === 'draft'
    ? 'This wording is platform-authored and has not been reconciled line by line against the '
      + 'publisher’s own document.'
    : 'The copilot was given this and its configured guidance, and nothing else about you.'}</span>
      </div>
    </div>`;

  res.send(shell(def.label, `
    ${subjectBlock}
    <div class="esg-stack">
      ${view.copilotAnswer(answer)}
      <p class="esg-small esg-prose">The copilot cannot accept a proposal, set an evidence level,
        mark anything verified or answer on your behalf. It returns words; every action stays
        yours.</p>
    </div>`, 'One question, about one thing, answered from what is configured for it.'));
}));

module.exports = router;
