'use strict';

const express = require('express');
const { query } = require('../db');
const { layout, esc, emptyState, frameworkLabel } = require('../utils/layout');
const sedg = require('../data/sedgV2');
const { scoreAssessment, loadActiveScheme } = require('../services/scoringEngine');
const { generateRecommendations } = require('../services/aiAdvisor');
const { electricityToCo2e, fuelToCo2e } = require('../services/carbonEngine');
const { mirrorStatus } = require('../services/verraService');

const router = express.Router();

const companyIdOf = (req) => req.user && req.user.company_id;
const num = (v) => { const n = parseFloat(v); return Number.isFinite(n) ? n : null; };

// ── Dashboard ──────────────────────────────────────────────────────────────
router.get('/dashboard', async (req, res, next) => {
  try {
    const cid = companyIdOf(req);
    const { rows: assess } = await query(
      `SELECT id, reporting_year, status, framework_code, framework_version
         FROM esg_assessments WHERE company_id = $1 AND status <> 'archived'
        ORDER BY reporting_year DESC LIMIT 1`, [cid]);

    if (!assess[0]) {
      return res.send(layout('Dashboard', `
        ${emptyState('instrumented_but_empty', {
          title: 'No assessment yet',
          body: 'Your ESG score is calculated from an assessment. Start one to see it.' })}
        <div style="text-align:center"><a class="btn btn-primary" href="/assessment">Start an assessment</a></div>`,
        req.user, '/dashboard'));
    }

    const a = assess[0];
    const { rows: scores } = await query(
      `SELECT scope, score_0_100, band_code, points_earned, points_available,
              indicators_total, indicators_answered, indicators_na,
              weighting_version, framework_version, engine_version
         FROM esg_scores WHERE assessment_id = $1`, [a.id]);
    const by = Object.fromEntries(scores.map((s) => [s.scope, s]));
    const overall = by.OVERALL;

    if (!overall) {
      return res.send(layout('Dashboard',
        emptyState('instrumented_but_empty', {
          title: 'Assessment started, not scored yet',
          body: 'Answer the questionnaire and submit it — the score is computed from your answers, not estimated.' })
        + `<div style="text-align:center"><a class="btn btn-primary" href="/assessment/${esc(a.id)}">Continue</a></div>`,
        req.user, '/dashboard'));
    }

    const cards = ['E', 'S', 'G'].map((p) => {
      const s = by[p] || {};
      const label = { E: 'Environmental', S: 'Social', G: 'Governance' }[p];
      const unanswered = s.indicators_answered === 0;
      return `<div class="stat-card">
        <div class="sc-label">${label}</div>
        <div class="sc-value">${unanswered ? '—' : esc(s.score_0_100)}</div>
        <div class="sc-sub muted">${esc(s.indicators_answered)} of ${esc(s.indicators_total)} answered${
          s.indicators_na > 0 ? ` · ${esc(s.indicators_na)} N/A` : ''}</div>
      </div>`;
    }).join('');

    const { rows: recs } = await query(
      `SELECT pillar, points_missed, priority, narrative_en, source
         FROM esg_recommendations WHERE assessment_id = $1 AND source <> 'engine'
        ORDER BY points_missed DESC LIMIT 6`, [a.id]);

    const recHtml = recs.length ? recs.map((r) => `
      <div class="ai-insight">
        <span class="badge badge-${r.priority === 'high' ? 'danger' : r.priority === 'medium' ? 'warning' : 'neutral'}">${esc(r.priority)}</span>
        <p>${esc(r.narrative_en)}</p>
        <small class="muted">${esc(r.pillar)} · ${esc(r.points_missed)} points available${
          r.source === 'fallback_template' ? ' · written offline (AI unavailable)' : ''}</small>
      </div>`).join('')
      : emptyState('instrumented_but_empty', { title: 'No recommendations generated yet',
          body: 'Submit the assessment to generate them.' });

    res.send(layout('Dashboard', `
      <div class="card">
        <div style="display:flex;align-items:baseline;gap:16px;flex-wrap:wrap">
          <div><div class="muted">Overall ESG score</div>
            <div style="font-size:48px;font-weight:700;line-height:1">${esc(overall.score_0_100)}</div></div>
          <div><span class="badge badge-primary" style="font-size:16px">${esc(overall.band_code || 'Not banded')}</span></div>
        </div>
        <p class="muted" style="margin-top:12px">
          ${esc(a.framework_code)} v${esc(overall.framework_version)} ·
          weighting v${esc(overall.weighting_version)} ·
          engine v${esc(overall.engine_version)} ·
          reporting year ${esc(a.reporting_year)}
        </p>
        <p class="muted">Every figure here is computed from your answers by the scoring engine. No part of it is generated by AI.</p>
      </div>
      <div class="grid grid-3" style="margin:16px 0">${cards}</div>
      <div class="card"><h3>ESG profile</h3><canvas id="radar" height="240"></canvas></div>
      <h3 style="margin:24px 0 12px">🤖 Recommendations</h3>
      ${recHtml}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
      <script>
      (function(){
        var css = getComputedStyle(document.documentElement);
        var accent = css.getPropertyValue('--accent').trim();
        new Chart(document.getElementById('radar'), {
          type: 'radar',
          data: { labels: ['Environmental','Social','Governance'],
                  datasets: [{ label: 'Score', data: ${JSON.stringify(['E','S','G'].map((p) => Number((by[p] || {}).score_0_100) || 0))},
                    borderColor: accent, backgroundColor: css.getPropertyValue('--accent-bg').trim(), pointBackgroundColor: accent }] },
          options: { scales: { r: { min: 0, max: 100, ticks: { stepSize: 25 } } },
                     plugins: { legend: { display: false } }, responsive: true }
        });
      })();
      </script>`, req.user, '/dashboard'));
  } catch (err) { next(err); }
});

// ── Company profile ────────────────────────────────────────────────────────
router.get('/company', async (req, res, next) => {
  try {
    const { rows } = await query(
      `SELECT id, name, ssm_number, msic_code, industry_label, employee_count,
              annual_revenue_myr, state, grid_region, esg_maturity
         FROM esg_companies WHERE id = $1`, [companyIdOf(req)]);
    const c = rows[0] || {};
    const opt = (v, cur, label) => `<option value="${esc(v)}"${cur === v ? ' selected' : ''}>${esc(label)}</option>`;
    res.send(layout('Company Profile', `
      <form class="card" method="post" action="/company">
        <div class="form-group"><label for="name">Company name</label>
          <input class="input" id="name" name="name" value="${esc(c.name || '')}" required></div>
        <div class="form-group"><label for="ssm_number">SSM registration number</label>
          <input class="input" id="ssm_number" name="ssm_number" value="${esc(c.ssm_number || '')}"></div>
        <div class="form-group"><label for="msic_code">MSIC code</label>
          <input class="input" id="msic_code" name="msic_code" value="${esc(c.msic_code || '')}"></div>
        <div class="form-group"><label for="employee_count">Number of employees</label>
          <input class="input" id="employee_count" name="employee_count" type="number" min="0" value="${esc(c.employee_count ?? '')}"></div>
        <div class="form-group"><label for="annual_revenue_myr">Annual revenue (RM)</label>
          <input class="input" id="annual_revenue_myr" name="annual_revenue_myr" type="number" min="0" step="0.01" value="${esc(c.annual_revenue_myr ?? '')}"></div>
        <div class="form-group"><label for="grid_region">Electricity grid</label>
          <select class="input" id="grid_region" name="grid_region" required>
            <option value="">Select…</option>
            ${opt('peninsular', c.grid_region, 'Peninsular Malaysia (TNB)')}
            ${opt('sabah', c.grid_region, 'Sabah &amp; Labuan (SESB)')}
            ${opt('sarawak', c.grid_region, 'Sarawak (Sarawak Energy)')}
          </select>
          <small class="muted">Required for Scope 2. The three grids differ by up to 3.7x, so this cannot be defaulted.</small></div>
        <button class="btn btn-primary" type="submit">Save</button>
      </form>`, req.user, '/company'));
  } catch (err) { next(err); }
});

router.post('/company', async (req, res, next) => {
  try {
    const b = req.body;
    const grid = ['peninsular', 'sabah', 'sarawak'].includes(b.grid_region) ? b.grid_region : null;
    await query(
      `UPDATE esg_companies SET name=$2, ssm_number=NULLIF($3,''), msic_code=NULLIF($4,''),
              employee_count=$5, annual_revenue_myr=$6, grid_region=$7
        WHERE id=$1`,
      [companyIdOf(req), String(b.name || '').trim(), String(b.ssm_number || '').trim(),
       String(b.msic_code || '').trim(), num(b.employee_count), num(b.annual_revenue_myr), grid]);
    res.redirect('/company');
  } catch (err) { next(err); }
});

// ── Assessment ─────────────────────────────────────────────────────────────
router.get('/assessment', async (req, res, next) => {
  try {
    const cid = companyIdOf(req);
    const { rows } = await query(
      `SELECT a.id, a.reporting_year, a.status, a.framework_code, a.framework_version,
              (SELECT score_0_100 FROM esg_scores s WHERE s.assessment_id = a.id AND s.scope='OVERALL') AS overall
         FROM esg_assessments a WHERE a.company_id = $1 AND a.status <> 'archived'
        ORDER BY a.reporting_year DESC`, [cid]);
    const list = rows.length ? `<table class="table"><thead><tr>
        <th>Year</th><th>Framework</th><th>Status</th><th>Score</th><th></th></tr></thead><tbody>
        ${rows.map((r) => `<tr><td>${esc(r.reporting_year)}</td>
          <td>${esc(r.framework_code)} v${esc(r.framework_version)}</td>
          <td><span class="badge">${esc(r.status)}</span></td>
          <td>${r.overall === null || r.overall === undefined ? '—' : esc(r.overall)}</td>
          <td><a class="btn btn-outline" href="/assessment/${esc(r.id)}">Open</a></td></tr>`).join('')}
        </tbody></table>` : emptyState('instrumented_but_empty', { title: 'No assessments yet' });

    res.send(layout('ESG Assessment', `
      <div class="card"><h3>Start an assessment</h3>
        <form method="post" action="/assessment" style="display:flex;gap:12px;align-items:flex-end;flex-wrap:wrap">
          <div class="form-group" style="margin:0"><label for="year">Reporting year</label>
            <input class="input" id="year" name="reporting_year" type="number" min="2015" max="2100"
                   value="${new Date().getFullYear() - 1}" required></div>
          <button class="btn btn-primary" type="submit">Create</button>
        </form></div>
      <div class="table-wrap" style="margin-top:16px">${list}</div>`, req.user, '/assessment'));
  } catch (err) { next(err); }
});

router.post('/assessment', async (req, res, next) => {
  try {
    const cid = companyIdOf(req);
    const year = parseInt(req.body.reporting_year, 10);
    if (!Number.isInteger(year)) return res.redirect('/assessment');

    const { rows: f } = await query(
      `SELECT id, code, version FROM esg_frameworks
        WHERE framework_kind = 'entity_disclosure' AND is_active ORDER BY effective_from DESC NULLS LAST LIMIT 1`);
    if (!f[0]) throw new Error('No active entity-disclosure framework is seeded');
    const scheme = await loadActiveScheme();

    const { rows } = await query(
      `INSERT INTO esg_assessments
         (company_id, framework_id, framework_code, framework_version,
          weighting_scheme_id, weighting_version, reporting_year, created_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
       ON CONFLICT (company_id, framework_id, reporting_year) WHERE status <> 'archived'
       DO UPDATE SET updated_at = now()
       RETURNING id`,
      [cid, f[0].id, f[0].code, f[0].version, scheme.id, scheme.version, year, req.user.id]);
    res.redirect(`/assessment/${rows[0].id}`);
  } catch (err) { next(err); }
});

router.get('/assessment/:id', async (req, res, next) => {
  try {
    const cid = companyIdOf(req);
    const { rows: a } = await query(
      `SELECT id, framework_id, framework_code, framework_version, reporting_year, status
         FROM esg_assessments WHERE id = $1 AND company_id = $2`, [req.params.id, cid]);
    if (!a[0]) return res.status(404).send(layout('Not found',
      emptyState('zero', { title: 'Assessment not found', body: 'It may belong to another company.' }), req.user, '/assessment'));

    const [{ rows: inds }, { rows: resp }] = await Promise.all([
      query(`SELECT id, code, pillar, tier, question_en, guidance_en, response_type, unit,
                    weight, allows_na, mapping_status
               FROM esg_indicators WHERE framework_id = $1 AND is_active ORDER BY pillar, sort_order`,
            [a[0].framework_id]),
      query(`SELECT indicator_id, option_code, value_numeric, is_na, evidence_tier
               FROM esg_responses WHERE assessment_id = $1`, [req.params.id]),
    ]);
    const byInd = Object.fromEntries(resp.map((r) => [r.indicator_id, r]));

    const field = (i) => {
      const r = byInd[i.id] || {};
      const sel = (v) => (String(r.option_code) === v ? ' selected' : '');
      if (i.response_type === 'quantitative') {
        return `<input class="input" name="v_${i.id}" type="number" step="any" min="0"
                  value="${esc(r.value_numeric ?? '')}" placeholder="${esc(i.unit || '')}">`;
      }
      if (i.response_type === 'maturity_0_4') {
        return `<select class="input" name="o_${i.id}"><option value="">Not answered</option>
          ${[0, 1, 2, 3, 4].map((n) => `<option value="${n}"${sel(String(n))}>Level ${n}</option>`).join('')}</select>`;
      }
      if (i.response_type === 'yes_no') {
        return `<select class="input" name="o_${i.id}"><option value="">Not answered</option>
          <option value="yes"${sel('yes')}>Yes</option><option value="no"${sel('no')}>No</option></select>`;
      }
      return `<select class="input" name="o_${i.id}"><option value="">Not answered</option>
        <option value="yes"${sel('yes')}>Yes</option>
        <option value="partial"${sel('partial')}>Partially</option>
        <option value="no"${sel('no')}>No</option></select>`;
    };

    const section = (p, title) => {
      const list = inds.filter((i) => i.pillar === p);
      if (!list.length) return '';
      return `<div class="card" style="margin-bottom:16px"><h3>${esc(title)}</h3>
        ${list.map((i) => {
          const r = byInd[i.id] || {};
          return `<div class="form-group" style="border-top:1px solid var(--border);padding-top:14px">
            <label for="o_${esc(i.id)}"><strong>${esc(i.code)}</strong> ${esc(i.question_en)}
              ${i.mapping_status === 'draft' ? '<span class="badge badge-warning" title="Platform-authored mapping, not yet reconciled against the official framework document">draft</span>' : ''}
            </label>
            ${i.guidance_en ? `<small class="muted">${esc(i.guidance_en)}</small>` : ''}
            <div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:6px">
              <div style="flex:2;min-width:180px">${field(i)}</div>
              <div style="flex:1;min-width:150px">
                <select class="input" name="e_${esc(i.id)}" aria-label="Evidence level">
                  <option value="self_declared"${r.evidence_tier === 'self_declared' || !r.evidence_tier ? ' selected' : ''}>Self-declared</option>
                  <option value="documented"${r.evidence_tier === 'documented' ? ' selected' : ''}>Documented</option>
                  <option value="verified"${r.evidence_tier === 'verified' ? ' selected' : ''}>Third-party verified</option>
                </select></div>
              ${i.allows_na ? `<label style="display:flex;align-items:center;gap:6px;font-size:13px">
                <input type="checkbox" name="na_${esc(i.id)}"${r.is_na ? ' checked' : ''}> Not applicable</label>` : ''}
            </div></div>`;
        }).join('')}</div>`;
    };

    res.send(layout(`Assessment ${a[0].reporting_year}`, `
      <div class="ai-insight" style="margin-bottom:16px">
        <strong>How this is scored.</strong> Answers marked <em>self-declared</em> earn 60% of the
        available points, <em>documented</em> 85%, <em>third-party verified</em> 100%. That is
        deliberate: a screening that awards full marks for unevidenced self-assessment is worth
        nothing to the bank or buyer reading it. Attaching documents you already hold is the
        cheapest way to raise your score.
      </div>
      <form method="post" action="/assessment/${esc(a[0].id)}">
        ${section('E', 'Environmental')}${section('S', 'Social')}${section('G', 'Governance')}
        <div style="display:flex;gap:12px">
          <button class="btn btn-primary" type="submit" name="action" value="save">Save</button>
          <button class="btn btn-primary" type="submit" name="action" value="submit">Save &amp; calculate score</button>
        </div>
      </form>`, req.user, '/assessment'));
  } catch (err) { next(err); }
});

router.post('/assessment/:id', async (req, res, next) => {
  try {
    const cid = companyIdOf(req);
    const { rows: a } = await query(
      `SELECT id, framework_id FROM esg_assessments WHERE id = $1 AND company_id = $2`,
      [req.params.id, cid]);
    if (!a[0]) return res.status(404).send('Not found');

    const { rows: inds } = await query(
      `SELECT id, response_type, allows_na FROM esg_indicators WHERE framework_id = $1 AND is_active`,
      [a[0].framework_id]);

    for (const i of inds) {
      const isNa   = i.allows_na && Boolean(req.body[`na_${i.id}`]);
      const opt    = req.body[`o_${i.id}`];
      const valRaw = req.body[`v_${i.id}`];
      const val    = num(valRaw);
      const tier   = ['self_declared', 'documented', 'verified'].includes(req.body[`e_${i.id}`])
                     ? req.body[`e_${i.id}`] : 'self_declared';

      const answered = isNa || (opt !== undefined && opt !== '') || val !== null;
      if (!answered) {
        await query(`DELETE FROM esg_responses WHERE assessment_id=$1 AND indicator_id=$2`, [a[0].id, i.id]);
        continue;
      }
      await query(
        `INSERT INTO esg_responses (assessment_id, indicator_id, option_code, value_numeric, is_na, evidence_tier, answered_by)
         VALUES ($1,$2,NULLIF($3,''),$4,$5,$6,$7)
         ON CONFLICT (assessment_id, indicator_id) DO UPDATE SET
           option_code = EXCLUDED.option_code, value_numeric = EXCLUDED.value_numeric,
           is_na = EXCLUDED.is_na, evidence_tier = EXCLUDED.evidence_tier, answered_by = EXCLUDED.answered_by`,
        [a[0].id, i.id, opt === undefined ? '' : String(opt), val, isNa, tier, req.user.id]);
    }

    if (req.body.action === 'submit') {
      await query(`UPDATE esg_assessments SET status='submitted', submitted_at=now() WHERE id=$1`, [a[0].id]);
      await scoreAssessment(a[0].id);
      // AI phrasing is best-effort and must never block the score. The engine
      // has already written every figure by this point.
      generateRecommendations(a[0].id, { companyId: cid, userId: req.user.id })
        .catch((e) => console.error('recommendations:', e.message));
      return res.redirect('/dashboard');
    }
    res.redirect(`/assessment/${a[0].id}`);
  } catch (err) { next(err); }
});

// ── Carbon ─────────────────────────────────────────────────────────────────
router.get('/carbon', async (req, res, next) => {
  try {
    const cid = companyIdOf(req);
    const [{ rows: co }, { rows: entries }] = await Promise.all([
      query(`SELECT grid_region FROM esg_companies WHERE id=$1`, [cid]),
      query(`SELECT id, period_start, period_end, scope, category, activity_amount, activity_unit,
                    kg_co2e, factor_value_used, factor_version_used, factor_source_used,
                    factor_verification_used, is_provisional
               FROM esg_carbon_entries WHERE company_id=$1 ORDER BY period_start DESC LIMIT 50`, [cid]),
    ]);
    const grid = co[0] && co[0].grid_region;

    const table = entries.length ? `<table class="table"><thead><tr>
      <th>Period</th><th>Scope</th><th>Activity</th><th>Factor</th><th>kg CO2e</th></tr></thead><tbody>
      ${entries.map((e) => `<tr${e.is_provisional ? ' class="provisional"' : ''}>
        <td>${esc(e.period_start)} → ${esc(e.period_end)}</td>
        <td>Scope ${esc(e.scope)}</td>
        <td>${esc(e.activity_amount)} ${esc(e.activity_unit)}</td>
        <td><small>${esc(e.factor_value_used)} · v${esc(e.factor_version_used)}
          ${e.is_provisional ? '<span class="badge badge-warning">provisional</span>' : ''}</small></td>
        <td><strong>${esc(e.kg_co2e)}</strong></td></tr>`).join('')}
      </tbody></table>` : emptyState('instrumented_but_empty', { title: 'No carbon entries yet' });

    res.send(layout('Carbon', `
      ${!grid ? `<div class="ai-insight"><strong>Set your electricity grid first.</strong>
        Scope 2 cannot be calculated without it — Peninsular and Sarawak factors differ by 3.7x.
        <a href="/company">Company profile →</a></div>` : `
      <div class="card"><h3>Add an entry</h3>
        <form method="post" action="/carbon" style="display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(160px,1fr))">
          <div class="form-group" style="margin:0"><label for="kind">Type</label>
            <select class="input" id="kind" name="kind">
              <option value="electricity">Electricity (Scope 2)</option>
              <option value="FUEL_DIESEL">Diesel (Scope 1)</option>
              <option value="FUEL_PETROL">Petrol (Scope 1)</option>
            </select></div>
          <div class="form-group" style="margin:0"><label for="amount">Amount</label>
            <input class="input" id="amount" name="amount" type="number" step="any" min="0" required></div>
          <div class="form-group" style="margin:0"><label for="period_start">From</label>
            <input class="input" id="period_start" name="period_start" type="date" required></div>
          <div class="form-group" style="margin:0"><label for="period_end">To</label>
            <input class="input" id="period_end" name="period_end" type="date" required></div>
          <div style="display:flex;align-items:flex-end"><button class="btn btn-primary" type="submit">Add</button></div>
        </form>
        <small class="muted">Diesel and petrol factors are placeholders pending a sourced Malaysian
        figure. Entries using them are stored and shown, and marked provisional — never presented as verified.</small>
      </div>`}
      <div class="table-wrap" style="margin-top:16px">${table}</div>`, req.user, '/carbon'));
  } catch (err) { next(err); }
});

router.post('/carbon', async (req, res, next) => {
  try {
    const cid = companyIdOf(req);
    const { rows: co } = await query(`SELECT grid_region FROM esg_companies WHERE id=$1`, [cid]);
    const amount = num(req.body.amount);
    if (amount === null || amount < 0) return res.redirect('/carbon');

    const calc = req.body.kind === 'electricity'
      ? await electricityToCo2e(amount, co[0] && co[0].grid_region)
      : await fuelToCo2e(amount, req.body.kind);

    await query(
      `INSERT INTO esg_carbon_entries
         (company_id, period_start, period_end, scope, category, activity_amount, activity_unit,
          factor_id, factor_value_used, factor_version_used, factor_source_used,
          factor_verification_used, is_provisional, kg_co2e, created_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,
      [cid, req.body.period_start, req.body.period_end,
       req.body.kind === 'electricity' ? 2 : 1,
       req.body.kind === 'electricity' ? 'grid_electricity' : 'mobile_combustion',
       calc.activity_amount, calc.activity_unit, calc.factor_id, calc.factor_value_used,
       calc.factor_version_used, calc.factor_source_used, calc.factor_verification_used,
       calc.is_provisional, calc.kg_co2e, req.user.id]);
    res.redirect('/carbon');
  } catch (err) { next(err); }
});

// ── Verra ──────────────────────────────────────────────────────────────────
router.get('/governance', async (req, res, next) => {
  try {
    const status = await mirrorStatus();
    const q = String(req.query.q || '').trim();
    let results = [];
    if (q) {
      const { rows } = await query(
        `SELECT verra_project_id, name, country, methodology_code, status
           FROM esg_verra_projects
          WHERE name ILIKE $1 OR country ILIKE $1 OR methodology_code ILIKE $1
          ORDER BY name LIMIT 50`, [`%${q}%`]);
      results = rows;
    }
    const body = status.state === 'populated'
      ? `<form method="get" style="display:flex;gap:10px;margin-bottom:16px">
           <input class="input" name="q" value="${esc(q)}" placeholder="Project, country or methodology">
           <button class="btn btn-primary">Search</button></form>
         ${q ? (results.length ? `<table class="table"><thead><tr><th>ID</th><th>Name</th><th>Country</th><th>Methodology</th><th>Status</th></tr></thead><tbody>
            ${results.map((r) => `<tr><td>${esc(r.verra_project_id)}</td><td>${esc(r.name)}</td>
              <td>${esc(r.country)}</td><td>${esc(r.methodology_code)}</td><td>${esc(r.status)}</td></tr>`).join('')}
            </tbody></table>
            <small class="text-sm">Records mirrored from a public carbon crediting registry. Metadata and links only.</small>`
          : emptyState('zero', { title: 'No matches', body: `Nothing in the mirror matches "${q}".` })) : ''}`
      : emptyState(status.state, {
          title: status.state === 'uninstrumented' ? 'Registry mirror is not switched on' : 'Registry mirror is empty',
          body: status.state === 'uninstrumented'
            ? 'Registry ingest has not been configured, so nothing writes to this table yet. See the deployment notes for the environment variables it needs.'
            : 'Ingest is configured and working — the sync has not run yet or returned no records.' });

    res.send(layout('Governance & Recognition', `
      <h3 class="section-title">Carbon Crediting Registry (public reference)</h3>
      <div class="ai-insight" style="margin-bottom:16px">
        <strong>What this is.</strong> A local mirror of a public carbon-crediting registry, for
        carbon-credit lookup. That registry certifies individual carbon <em>projects</em> and issues
        tradable carbon units — it does not rate companies on E, S and G, so nothing here feeds your
        ESG score. The scoring engine refuses to score against it by design.
      </div>
      <div class="grid grid-3" style="margin-bottom:16px">
        <div class="stat-card"><div class="sc-label">Projects mirrored</div><div class="sc-value">${esc(status.projects)}</div></div>
        <div class="stat-card"><div class="sc-label">Methodologies</div><div class="sc-value">${esc(status.methodologies)}</div></div>
        <div class="stat-card"><div class="sc-label">Last fetch</div><div class="sc-value" style="font-size:16px">${status.last_fetch ? esc(new Date(status.last_fetch).toISOString().slice(0, 10)) : '—'}</div></div>
      </div>
      ${body}`, req.user, '/governance'));
  } catch (err) { next(err); }
});

// ── Reports & documents (sprint 2 surfaces, honestly labelled) ─────────────
router.get('/reports', (req, res) => {
  res.send(layout('Reports', emptyState('uninstrumented', {
    title: 'Report generation is not built yet',
    body: 'The scoring data it needs exists. PDF/DOCX/XLSX export is sprint 2 — this page is here so the gap is visible rather than hidden behind a broken button.',
  }), req.user, '/reports'));
});

// ═══════════════════════════════════════════════════════════════════════════
// SECTION SCREENS
//
// One navigable screen per requirement section. Each states honestly what it
// is: built, not-instrumented, or not-built. NO DEAD CONTROLS (contract
// §4.3c) — there is no filter that filters nothing, no toggle bound to
// nothing, and no Save that never posts on any page below. If it does not
// act, it does not render.
//
// The scope list on each page is STATIC TEXT describing what the section will
// cover. It is a scope statement, not a claim that any of it works.
// ═══════════════════════════════════════════════════════════════════════════

/** A scope list. Deliberately not a checklist and not a progress bar — both
 *  would imply measured completion that nothing here measures. */
const scope = (title, items) => `
  <div class="card">
    <h3 class="card-title">${esc(title)}</h3>
    <ul>${items.map((i) => `<li>${esc(i)}</li>`).join('')}</ul>
  </div>`;

/** `.coming-soon` — defined at modus-design-system.css:986. Not built at all. */
const comingSoon = (title, body, phase) => `
  <div class="coming-soon">
    <div class="coming-soon-icon">🚧</div>
    <h2>${esc(title)}</h2>
    <p>${esc(body)}</p>
    ${phase ? `<div class="coming-soon-phase">${esc(phase)}</div>` : ''}
  </div>`;

// ── Frameworks — the real one ──────────────────────────────────────────────
router.get('/frameworks', (req, res) => {
  const { PROVENANCE: p, COUNTS: c } = sedg;

  const tierBadge = (tier) => {
    const tone = { Basic: 'badge-success', Intermediate: 'badge-info', Advanced: 'badge-warning' }[tier] || '';
    return `<span class="badge ${tone}">${esc(tier)}</span>`;
  };

  const pillars = sedg.grouped().map((g) => `
    <div class="card">
      <h3 class="card-title">${esc(g.pillarName)} — ${g.topics.reduce((n, t) => n + t.disclosures.length, 0)} disclosures</h3>
      ${g.topics.map((t) => `
        <h4>${esc(t.topic)}</h4>
        <div class="table-wrap">
          <table>
            <thead><tr><th>Code</th><th>Tier</th><th>Disclosure</th><th>Unit</th></tr></thead>
            <tbody>
              ${t.disclosures.map((d) => `<tr>
                <td>${esc(d.code)}${d.newInV2 ? ' <span class="badge badge-info">new in v2</span>' : ''}</td>
                <td>${tierBadge(d.tier)}</td>
                <td>${esc(d.text)}</td>
                <td>${esc(d.unit)}</td>
              </tr>`).join('')}
            </tbody>
          </table>
        </div>`).join('')}
    </div>`).join('');

  const others = `
    <div class="card">
      <h3 class="card-title">Other frameworks</h3>
      <p class="text-sm">Named so the gap is visible. None of these is loaded, mapped or scored.</p>
      <div class="table-wrap">
        <table>
          <thead><tr><th>Framework</th><th>Status</th><th>Note</th></tr></thead>
          <tbody>
            ${sedg.OTHER_FRAMEWORKS.map((f) => `<tr>
              <td>${esc(f.name)}</td>
              <td><span class="badge badge-warning">Not loaded</span></td>
              <td>${esc(f.note)}</td>
            </tr>`).join('')}
          </tbody>
        </table>
      </div>
    </div>`;

  res.send(layout('Frameworks', `
    <div class="card">
      <h3 class="card-title">${esc(p.document)}</h3>
      <p><strong>Publisher.</strong> ${esc(p.publisher)}, ${esc(p.publisherNote)}. Published ${esc(p.published)}.</p>
      <p><strong>Source.</strong> <a href="${esc(p.pdf)}" rel="noreferrer noopener" target="_blank">${esc(p.pdf)}</a></p>
      <div class="grid grid-3">
        <div class="stat-card"><div class="sc-label">Disclosures</div><div class="sc-value">${c.total}</div></div>
        <div class="stat-card"><div class="sc-label">E / S / G</div><div class="sc-value">${c.pillars.E} / ${c.pillars.S} / ${c.pillars.G}</div></div>
        <div class="stat-card"><div class="sc-label">Basic / Inter. / Adv.</div><div class="sc-value">${c.tiers.Basic} / ${c.tiers.Intermediate} / ${c.tiers.Advanced}</div></div>
      </div>
      <p class="text-sm">${esc(p.countNote)}</p>
    </div>

    <div class="alert">
      <span class="badge badge-warning">SEDG-ALIGNED (DRAFT)</span>
      <p><strong>What this platform claims, precisely.</strong> The assessment you take on this
      platform is <em>${esc(frameworkLabel('MODUS_SEDG_ALIGNED', '0.9-draft'))}</em>. The
      ${c.total} disclosures below are the official published set it will be reconciled against.
      They are <strong>not implemented</strong>: they are not loaded as questions, not answerable,
      and not scored. This platform is not SEDG-compliant and does not claim to be.</p>
    </div>

    ${pillars}
    ${others}`, req.user, '/frameworks'));
});

// ── Analytics — table exists, nothing writes to it ─────────────────────────
router.get('/analytics', (req, res) => {
  res.send(layout('Analytics', `
    ${emptyState('uninstrumented', {
      title: 'Analytics is not instrumented yet',
      body: 'Scores are stored per assessment, but nothing yet writes the time series, peer '
          + 'benchmarks or trend aggregates this section needs. It is not switched on, rather than empty.',
    })}
    ${scope('What this section will cover', [
      'Score trend over time, per pillar and overall',
      'Peer benchmarking by sector and company size',
      'Disclosure completeness against the official framework',
      'Carbon intensity trend against reported activity',
      'Evidence coverage — which answers are documented',
    ])}`, req.user, '/analytics'));
});

// ── KPIs — table exists, nothing writes to it ──────────────────────────────
router.get('/kpis', (req, res) => {
  res.send(layout('KPIs', `
    ${emptyState('uninstrumented', {
      title: 'KPI tracking is not instrumented yet',
      body: 'No target has been set and nothing writes KPI values. An empty chart here would '
          + 'claim a capability that does not exist yet.',
    })}
    ${scope('What this section will cover', [
      'Targets per pillar, set by the company',
      'Actual against target, per reporting period',
      'Emissions intensity and reduction targets',
      'Training hours, turnover and safety rates',
      'Alerting when a KPI moves away from its target',
    ])}`, req.user, '/kpis'));
});

// ── AI Assistant — not built as a standalone surface ───────────────────────
// The AI layer itself IS real and reachable today: `generateRecommendations`
// runs on the assessment result and every call is logged to
// esg_ai_interactions. What does not exist is a conversational assistant, so
// this is coming-soon rather than uninstrumented — and it says where the
// working AI actually is, rather than implying there is none.
router.get('/assistant', (req, res) => {
  res.send(layout('AI Assistant', `
    ${comingSoon('A conversational assistant is not built yet',
      'AI is already working elsewhere in this platform: your assessment result carries '
      + 'AI-generated recommendations, and the model is never allowed to author a figure. '
      + 'A general-purpose assistant surface is a separate piece of work.',
      'Available today: open an assessment result to see AI recommendations')}
    ${scope('What this section will cover', [
      'Ask questions about your own assessment and evidence',
      'Guidance on what a specific disclosure is asking for',
      'Drafting narrative answers for review — never auto-submitted',
      'Trilingual (EN / BM / 中文)',
      'The model never produces a figure — the same guard the rest of the platform uses',
    ])}`, req.user, '/assistant'));
});

// ── Workflow — not built ───────────────────────────────────────────────────
router.get('/workflow', (req, res) => {
  res.send(layout('Workflow', `
    ${comingSoon('Review and approval workflow is not built yet',
      'Assessments are currently completed and scored in one step, with no review stage. '
      + 'Nothing in the database tracks an approval, so there is nothing to show here yet.',
      'Not started')}
    ${scope('What this section will cover', [
      'Submit an assessment for internal review before it is final',
      'Reviewer and approver roles, with an audit trail',
      'Return-for-revision with comments against specific answers',
      'Period locking once a reporting year is signed off',
      'Notification when an action is waiting on someone',
    ])}`, req.user, '/workflow'));
});

// ── Users & Roles — not built ──────────────────────────────────────────────
router.get('/users', (req, res) => {
  res.send(layout('Users & Roles', `
    ${comingSoon('User and role management is not built yet',
      'Accounts exist and are authenticated, and every route is authorised server-side. '
      + 'What is missing is the screen to invite people and change their role — that is '
      + 'currently a database operation.',
      'Not started')}
    ${scope('What this section will cover', [
      'Invite a colleague by email',
      'Assign and change roles, granted by an administrator and never self-claimed',
      'Remove access, with the change recorded',
      'See who last signed in',
      'Audit trail of role changes',
    ])}`, req.user, '/users'));
});

// ── Integrations — not built ───────────────────────────────────────────────
router.get('/integrations', (req, res) => {
  res.send(layout('Integrations', `
    ${comingSoon('Integrations are not built yet',
      'No third-party connection is configured, and none is running in the background. '
      + 'Showing a list of logos with Connect buttons that do nothing would be worse than '
      + 'showing this.',
      'Not started')}
    ${scope('What this section will cover', [
      'Utility and energy data import for the carbon calculator',
      'Accounting system import for the financial disclosures',
      'HR system import for headcount, turnover and training hours',
      'Document storage for evidence files',
      'Export to a customer’s supplier portal',
    ])}`, req.user, '/integrations'));
});


module.exports = router;
